### ISSUE TITLE
build fails on docker push registry.heroku.com/laphil-dev/web

### ISSUE THREAD

**Issue by robdeadtech** [blitzagency/cookiecutter-django#13]
I haven't tried to reproduce this yet but I thought I'd mention it. 
If I run `make heroku.deploy ENV_NAME=dev` the build starts and runs successfully to the point of `docker push registry.heroku.com/laphil-dev/web` This step fails with an `unauthorized: authentication required` error

*My workaround:*
If I run `heroku container:login` at this point I successfully authenticate (no user intervention required) and then I can  run `docker push registry.heroku.com/laphil-dev/web` and my pushes complete successfully.

**Comment by seawolf42** [comment]
unable to reproduce
