### ISSUE TITLE
Install Redirect Middleware

### ISSUE THREAD

**Issue by aubricus** [blitzagency/cookiecutter-django#35]
Looks like contrib.django.redirects is installed by default but the middleware is not.

Link to docs on how to install (TLDR; Redirect middleware, `"django.contrib.redirects.middleware.RedirectFallbackMiddleware"`, can come last)

https://docs.djangoproject.com/en/2.0/ref/contrib/redirects/

**Comment by seawolf42** [comment]
fixed by #39
